/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary": "#aca3ff",
        "primary-dim": "#6f5fea",
        "secondary": "#00d2ff",
        "secondary-dim": "#00c3ed",
        "tertiary": "#e69dff",
        "error": "#ff6e84",
        "background": "#0e0e12",
        "surface": "#0e0e12",
        "surface-container": "#19191e",
        "surface-container-low": "#131317",
        "surface-container-high": "#1f1f25",
        "surface-container-highest": "#25252b",
        "surface-bright": "#2c2b32",
        "surface-variant": "#25252b",
        "on-surface": "#fcf8fe",
        "on-surface-variant": "#acaab0",
        "on-primary": "#27009a",
        "on-secondary": "#004253",
        "on-primary-fixed": "#000000",
        "on-primary-container": "#1d007a",
        "outline-variant": "#48474c",
        "outline": "#76757a",
      },
      fontFamily: {
        headline: ["Manrope", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Space Grotesk", "sans-serif"],
        mono: ["JetBrains Mono", "monospace"],
      },
      animation: {
        'fade-in': 'fadeIn 0.5s ease-out',
        'slide-up': 'slideUp 0.6s cubic-bezier(0.16,1,0.3,1)',
        'slide-in-left': 'slideInLeft 0.5s cubic-bezier(0.16,1,0.3,1)',
        'ping-slow': 'ping 3s cubic-bezier(0,0,0.2,1) infinite',
        'float': 'float 6s ease-in-out infinite',
        'shimmer': 'shimmer 1.5s infinite',
      },
      keyframes: {
        fadeIn: { '0%': { opacity: '0' }, '100%': { opacity: '1' } },
        slideUp: { '0%': { opacity: '0', transform: 'translateY(30px)' }, '100%': { opacity: '1', transform: 'translateY(0)' } },
        slideInLeft: { '0%': { opacity: '0', transform: 'translateX(-20px)' }, '100%': { opacity: '1', transform: 'translateX(0)' } },
        float: { '0%,100%': { transform: 'translateY(0)' }, '50%': { transform: 'translateY(-10px)' } },
        shimmer: { '0%': { backgroundPosition: '200% 0' }, '100%': { backgroundPosition: '-200% 0' } },
      },
    },
  },
  plugins: [],
}